<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Lab.Application.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707;CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Lab.Application\Lab.Application.csproj" />
    <ProjectReference Include="..\..\src\Lab.Contracts\Lab.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Lab.Domain\Lab.Domain.csproj" />
    <ProjectReference Include="..\..\src\Lab.Infrastructure\Lab.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Lab.Migrations.Sqlite\Lab.Migrations.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
